In [120]:
import pandas as pd

In [121]:
matches = pd.read_csv("/Users/Harsh/Desktop/AML/matches.csv", index_col = 0)

In [122]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
38,4/25/22,20:00,Premier League,Matchweek 34,Mon,Home,D,0,0,Leeds United,...,Match Report,NaN,17,7,13.8,0,0,0,2022,Crystal Palace
36,4/25/22,20:00,Premier League,Matchweek 34,Mon,Away,D,0,0,Crystal Palace,...,Match Report,NaN,9,2,16.5,0,0,0,2022,Leeds United
53,4/24/22,14:00,Premier League,Matchweek 34,Sun,Home,W,1,0,West Ham,...,Match Report,NaN,25,4,18.4,0,0,1,2022,Chelsea
49,4/24/22,14:00,Premier League,Matchweek 34,Sun,Away,L,0,1,Chelsea,...,Match Report,NaN,6,2,14.0,0,0,0,2022,West Ham United
36,4/24/22,14:00,Premier League,Matchweek 34,Sun,Away,L,0,1,Burnley,...,Match Report,NaN,10,4,18.6,0,0,0,2022,Wolverhampton Wanderers

In [123]:
matches.shape

(1389, 27)

In [124]:
# 2 seasons * 20 squads * 38 matches

2 * 20 * 38

1520

In [125]:
# Missing Liverpool 2021-2022
matches["team"].value_counts()

team
Newcastle United            72
West Ham United             72
Manchester United           72
Brighton and Hove Albion    72
Southampton                 72
Crystal Palace              71
Manchester City             71
Leeds United                71
Arsenal                     71
Tottenham Hotspur           71
Burnley                     71
Wolverhampton Wanderers     71
Everton                     70
Chelsea                     70
Leicester City              70
Aston Villa                 70
Liverpool                   38
Fulham                      38
West Bromwich Albion        38
Sheffield United            38
Brentford                   34
Watford                     33
Norwich City                33
Name: count, dtype: int64

In [126]:
matches[matches["team"] == "Liverpool"].sort_values("date")

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
27,1/17/21,16:30,Premier League,Matchweek 19,Sun,Home,D,0,0,Manchester Utd,...,Match Report,NaN,17,3,17.1,0,0,0,2021,Liverpool
28,1/21/21,20:00,Premier League,Matchweek 18,Thu,Home,L,0,1,Burnley,...,Match Report,NaN,27,6,17.3,0,0,0,2021,Liverpool
30,1/28/21,20:00,Premier League,Matchweek 20,Thu,Away,W,3,1,Tottenham,...,Match Report,NaN,14,7,14.7,0,0,0,2021,Liverpool
31,1/31/21,16:30,Premier League,Matchweek 21,Sun,Away,W,3,1,West Ham,...,Match Report,NaN,14,5,15.3,0,0,0,2021,Liverpool
25,1/4/21,20:00,Premier League,Matchweek 17,Mon,Away,L,0,1,Southampton,...,Match Report,NaN,17,1,14.3,0,0,0,2021,Liverpool
7,10/17/20,12:30,Premier League,Matchweek 5,Sat,Away,D,2,2,Everton,...,Match Report,NaN,22,8,15.0,1,0,0,2021,Liverpool
9,10/24/20,20:00,Premier League,Matchweek 6,Sat,Home,W,2,1,Sheffield Utd,...,Match Report,NaN,17,5,18.2,1,0,0,2021,Liverpool
11,10/31/20,17:30,Premier League,Matchweek 7,Sat,Home,W,2,1,West Ham,...,Match Report,NaN,8,2,18.6,1,1,1,2021,Liverpool
6,10/4/20,19:15,Premier League,Matchweek 4,Sun,Away,L,2,7,Aston Villa,...,Match Report,NaN,14,8,15.8,1,0,0,2021,Liverpool
14,11/22/20,19:15,Premier League,Matchweek 9,Sun,Home,W,3,0,Leicester City,...,Match Report,NaN,24,12,11.9,0,0,0,2021,Liverpool
16,11/28/20,12:30,Premier League,Matchweek 10,Sat,Away,D,1,1,Brighton,...,Match Report,NaN,6,2,20.9,0,0,0,2021,Liverpool
13,11/8/20,16:30,Premier League,Matchweek 8,Sun,Away,D,1,1,Manchester City,...,Match Report,NaN,9,2,21.5,0,1,1,2021,Liverpool
20,12/13/20,16:30,Premier League,Matchweek 12,Sun,Away,D,1,1,Fulham,...,Match Report,NaN,11,5,20.0,1,1,1,2021,Liverpool
21,12/16/20,20:00,Premier League,Matchweek 13,Wed,Home,W,2,1,Tottenham,...,Match Report,NaN,17,11,15.5,0,0,0,2021,Liverpool
22,12/19/20,12:30,Premier League,Matchweek 14,Sat,Away,W,7,0,Crystal Palace,...,Match Report,NaN,14,7,13.2,1,0,0,2021,Liverpool
23,12/27/20,16:30,Premier League,Matchweek 15,Sun,Home,D,1,1,West Brom,...,Match Report,NaN,17,2,17.8,2,0,0,2021,Liverpool
24,12/30/20,20:00,Premier League,Matchweek 16,Wed,Away,D,0,0,Newcastle Utd,...,Match Report,NaN,11,4,16.7,0,0,0,2021,Liverpool
18,12/6/20,19:15,Premier League,Matchweek 11,Sun,Home,W,4,0,Wolves,...,Match Report,NaN,11,6,16.6,1,0,0,2021,Liverpool
34,2/13/21,12:30,Premier League,Matchweek 24,Sat,Away,L,1,3,Leicester City,...,Match Report,NaN,15,4,15.4,2,0,0,2021,Liverpool
36,2/20/21,17:30,Premier League,Matchweek 25,Sat,Home,L,0,2,Everton,...,Match Report,NaN,16,6,15.9,1,0,0,2021,Liverpool
37,2/28/21,19:15,Premier League,Matchweek 26,Sun,Away,W,2,0,Sheffield Utd,...,Match Report,NaN,15,8,14.2,0,0,0,2021,Liverpool
32,2/3/21,20:15,Premier League,Matchweek 22,Wed,Home,L,0,1,Brighton,...,Match Report,NaN,11,0,19.9,0,0,0,2021,Liverpool
33,2/7/21,16:30,Premier League,Matchweek 23,Sun,Home,L,1,4,Manchester City,...,Match Report,NaN,7,2,17.9,1,1,1,2021,Liverpool
41,3/15/21,20:00,Premier League,Matchweek 28,Mon,Away,W,1,0,Wolves,...,Match Report,NaN,12,4,15.9,0,0,0,2021,Liverpool
38,3/4/21,20:15,Premier League,Matchweek 29,Thu,Home,L,0,1,Chelsea,...,Match Report,NaN,7,1,18.4,0,0,0,2021,Liverpool
39,3/7/21,14:00,Premier League,Matchweek 27,Sun,Home,L,0,1,Fulham,...,Match Report,NaN,16,3,17.0,1,0,0,2021,Liverpool
44,4/10/21,15:00,Premier League,Matchweek 31,Sat,Home,W,2,1,Aston Villa,...,Match Report,NaN,23,8,16.7,1,0,0,2021,Liverpool
46,4/19/21,20:00,Premier League,Matchweek 32,Mon,Away,D,1,1,Leeds United,...,Match Report,NaN,17,7,15.7,0,0,0,2021,Liverpool
47,4/24/21,12:30,Premier League,Matchweek 33,Sat,Home,D,1,1,Newcastle Utd,...,Match Report,NaN,21,9,17.0,1,0,0,2021,Liverpool
42,4/3/21,20:00,Premier League,Matchweek 30,Sat,Away,W,3,0,Arsenal,...,Match Report,NaN,16,7,17.0,0,0,0,2021,Liverpool
49,5/13/21,20:15,Premier League,Matchweek 34,Thu,Away,W,4,2,Manchester Utd,...,Match Report,NaN,17,8,14.9,0,0,0,2021,Liverpool
50,5/16/21,16:30,Premier League,Matchweek 36,Sun,Away,W,2,1,West Brom,...,Match Report,NaN,26,6,16.9,1,0,0,2021,Liverpool
51,5/19/21,20:15,Premier League,Matchweek 37,Wed,Away,W,3,0,Burnley,...,Match Report,NaN,20,3,15.5,1,0,0,2021,Liverpool
52,5/23/21,16:00,Premier League,Matchweek 38,Sun,Home,W,2,0,Crystal Palace,...,Match Report,NaN,19,5,14.2,1,0,0,2021,Liverpool
48,5/8/21,20:15,Premier League,Matchweek 35,Sat,Home,W,2,0,Southampton,...,Match Report,NaN,14,6,12.4,0,0,0,2021,Liverpool
1,9/12/20,17:30,Premier League,Matchweek 1,Sat,Home,W,4,3,Leeds United,...,Match Report,NaN,20,4,17.0,0,2,2,2021,Liverpool
2,9/20/20,16:30,Premier League,Matchweek 2,Sun,Away,W,2,0,Chelsea,...,Match Report,NaN,17,5,17.7,1,0,0,2021,Liverpool
4,9/28/20,20:00,Premier League,Matchweek 3,Mon,Home,W,3,1,Arsenal,...,Match Report,NaN,21,9,16.8,0,0,0,2021,Liverpool

In [127]:
matches["round"].value_counts()

round
Matchweek 34    39
Matchweek 8     39
Matchweek 15    39
Matchweek 14    39
Matchweek 12    39
Matchweek 11    39
Matchweek 10    39
Matchweek 9     39
Matchweek 7     39
Matchweek 24    39
Matchweek 6     39
Matchweek 5     39
Matchweek 4     39
Matchweek 3     39
Matchweek 2     39
Matchweek 1     39
Matchweek 17    39
Matchweek 23    39
Matchweek 26    39
Matchweek 16    39
Matchweek 25    39
Matchweek 32    39
Matchweek 19    39
Matchweek 20    39
Matchweek 31    39
Matchweek 29    39
Matchweek 28    39
Matchweek 13    39
Matchweek 27    37
Matchweek 21    37
Matchweek 30    37
Matchweek 22    37
Matchweek 18    37
Matchweek 33    32
Matchweek 38    20
Matchweek 37    20
Matchweek 36    20
Matchweek 35    20
Name: count, dtype: int64

In [128]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf                int64
ga                int64
opponent         object
xg              float64
xga             float64
poss              int64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh                int64
sot               int64
dist            float64
fk                int64
pk                int64
pkatt             int64
season            int64
team             object
dtype: object

In [129]:
matches["date"] = pd.to_datetime(matches["date"])

/var/folders/_c/dryy8y6545g9lbd6jb2d5g200000gn/T/ipykernel_71842/2174778740.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  matches["date"] = pd.to_datetime(matches["date"])

In [130]:
matches["target"] = (matches["result"] == "W").astype("int")

In [131]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,notes,sh,sot,dist,fk,pk,pkatt,season,team,target
38,2022-04-25,20:00,Premier League,Matchweek 34,Mon,Home,D,0,0,Leeds United,...,NaN,17,7,13.8,0,0,0,2022,Crystal Palace,0
36,2022-04-25,20:00,Premier League,Matchweek 34,Mon,Away,D,0,0,Crystal Palace,...,NaN,9,2,16.5,0,0,0,2022,Leeds United,0
53,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Home,W,1,0,West Ham,...,NaN,25,4,18.4,0,0,1,2022,Chelsea,1
49,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Away,L,0,1,Chelsea,...,NaN,6,2,14.0,0,0,0,2022,West Ham United,0
36,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Away,L,0,1,Burnley,...,NaN,10,4,18.6,0,0,0,2022,Wolverhampton Wanderers,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2020-09-12,17:30,Premier League,Matchweek 1,Sat,Away,L,3,4,Liverpool,...,NaN,6,3,17.5,1,0,0,2021,Leeds United,0
0,2020-09-12,20:00,Premier League,Matchweek 1,Sat,Away,W,2,0,West Ham,...,NaN,16,3,16.2,1,0,0,2021,Newcastle United,1
0,2020-09-12,15:00,Premier League,Matchweek 1,Sat,Home,W,1,0,Southampton,...,NaN,6,3,10.1,0,0,0,2021,Crystal Palace,1
0,2020-09-12,15:00,Premier League,Matchweek 1,Sat,Away,L,0,1,Crystal Palace,...,NaN,9,5,15.6,2,0,0,2021,Southampton,0
0,2020-09-12,12:30,Premier League,Matchweek 1,Sat,Home,L,0,3,Arsenal,...,NaN,5,2,26.0,0,0,0,2021,Fulham,0

In [132]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [133]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [134]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [135]:
matches["day_code"] = matches["date"].dt.dayofweek

In [136]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
38,2022-04-25,20:00,Premier League,Matchweek 34,Mon,Home,D,0,0,Leeds United,...,0,0,0,2022,Crystal Palace,0,1,9,20,0
36,2022-04-25,20:00,Premier League,Matchweek 34,Mon,Away,D,0,0,Crystal Palace,...,0,0,0,2022,Leeds United,0,0,6,20,0
53,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Home,W,1,0,West Ham,...,0,0,1,2022,Chelsea,1,1,21,14,6
49,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Away,L,0,1,Chelsea,...,0,0,0,2022,West Ham United,0,0,5,14,6
36,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Away,L,0,1,Burnley,...,0,0,0,2022,Wolverhampton Wanderers,0,0,4,14,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2020-09-12,17:30,Premier League,Matchweek 1,Sat,Away,L,3,4,Liverpool,...,1,0,0,2021,Leeds United,0,0,11,17,5
0,2020-09-12,20:00,Premier League,Matchweek 1,Sat,Away,W,2,0,West Ham,...,1,0,0,2021,Newcastle United,1,0,21,20,5
0,2020-09-12,15:00,Premier League,Matchweek 1,Sat,Home,W,1,0,Southampton,...,0,0,0,2021,Crystal Palace,1,1,17,15,5
0,2020-09-12,15:00,Premier League,Matchweek 1,Sat,Away,L,0,1,Crystal Palace,...,2,0,0,2021,Southampton,0,0,6,15,5
0,2020-09-12,12:30,Premier League,Matchweek 1,Sat,Home,L,0,3,Arsenal,...,0,0,0,2021,Fulham,0,1,0,12,5

In [137]:
from sklearn.ensemble import RandomForestClassifier

In [138]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [139]:
train = matches[matches["date"] < '2022-01-01']

In [140]:
test = matches[matches["date"] > '2022-01-01']

In [141]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [142]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [143]:
preds = rf.predict(test[predictors])

In [144]:
from sklearn.metrics import accuracy_score

In [145]:
acc = accuracy_score(test["target"], preds)

In [146]:
acc

0.5797101449275363

In [147]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [148]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0   1
actual
0          139  33
1           83  21

In [149]:
from sklearn.metrics import precision_score

precision_score(test["target"], preds)

0.3888888888888889

In [150]:
grouped_matches = matches.groupby("team")

In [151]:
group = grouped_matches.get_group("Manchester City").sort_values("date")

In [152]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [153]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
5,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Home,W,1,0,Arsenal,...,17,5,2.000000,2.333333,17.333333,4.666667,18.900000,1.333333,0.333333,0.333333
7,2020-10-24,12:30,Premier League,Matchweek 6,Sat,Away,D,1,1,West Ham,...,12,5,1.333333,2.000000,17.333333,3.666667,17.733333,0.666667,0.000000,0.000000
9,2020-10-31,12:30,Premier League,Matchweek 7,Sat,Away,W,1,0,Sheffield Utd,...,12,5,1.000000,0.666667,16.666667,4.333333,18.233333,0.666667,0.000000,0.000000
11,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Home,D,1,1,Liverpool,...,16,6,1.000000,0.333333,14.333333,6.666667,18.466667,1.000000,0.000000,0.000000
12,2020-11-21,17:30,Premier League,Matchweek 9,Sat,Away,L,0,2,Tottenham,...,17,5,1.000000,0.666667,12.000000,5.666667,19.366667,1.000000,0.000000,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2022-03-14,20:00,Premier League,Matchweek 29,Mon,Away,D,0,0,Crystal Palace,...,20,0,2.333333,1.333333,19.000000,7.000000,15.366667,0.333333,0.333333,0.333333
44,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Away,W,2,0,Burnley,...,15,5,1.666667,0.333333,18.333333,7.333333,16.000000,0.333333,0.000000,0.000000
46,2022-04-10,16:30,Premier League,Matchweek 32,Sun,Home,D,2,2,Liverpool,...,16,6,2.000000,0.333333,20.000000,6.666667,16.133333,0.333333,0.000000,0.000000
49,2022-04-20,20:00,Premier League,Matchweek 30,Wed,Home,W,3,0,Brighton,...,20,2,1.333333,0.666667,15.666667,4.666667,16.700000,0.333333,0.000000,0.000000
50,2022-04-23,15:00,Premier League,Matchweek 34,Sat,Home,W,5,1,Watford,...,15,5,2.333333,0.666667,15.333333,5.000000,17.200000,0.333333,0.000000,0.000000

In [154]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [155]:
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 6  2020-10-04  14:00  Premier League   Matchweek 4
                        7  2020-10-17  17:30  Premier League   Matchweek 5
                        9  2020-10-25  19:15  Premier League   Matchweek 6
                        11 2020-11-01  16:30  Premier League   Matchweek 7
                        13 2020-11-08  19:15  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 32 2022-03-13  14:00  Premier League  Matchweek 29
                        33 2022-03-18  20:00  Premier League  Matchweek 30
                        34 2022-04-02  15:00  Premier League  Matchweek 31
                        35 2022-04-08  20:00  Premier League  Matchweek 32
                        36 2022-04-24  14:00  Premier League  Matchweek 34

                            day venue result  gf  ga         opponent  ...  \
team                                                                   ...
Arsenal                 6   Sun  Home      W   2   1    Sheffield Utd  ...
                        7   Sat  Away      L   0   1  Manchester City  ...
                        9   Sun  Home      L   0   1   Leicester City  ...
                        11  Sun  Away      W   1   0   Manchester Utd  ...
                        13  Sun  Home      L   0   3      Aston Villa  ...
...                         ...   ...    ...  ..  ..              ...  ...
Wolverhampton Wanderers 32  Sun  Away      W   1   0          Everton  ...
                        33  Fri  Home      L   2   3     Leeds United  ...
                        34  Sat  Home      W   2   1      Aston Villa  ...
                        35  Fri  Away      L   0   1    Newcastle Utd  ...
                        36  Sun  Away      L   0   1          Burnley  ...

                            hour  day_code  gf_rolling  ga_rolling sh_rolling  \
team
Arsenal                 6     14         6    2.000000    1.333333   7.666667
                        7     17         5    1.666667    1.666667   5.333333
                        9     19         6    1.000000    1.666667   7.000000
                        11    16         6    0.666667    1.000000   9.666667
                        13    19         6    0.333333    0.666667   9.666667
...                          ...       ...         ...         ...        ...
Wolverhampton Wanderers 32    14         6    1.333333    1.000000  12.333333
                        33    20         4    1.666667    0.666667  12.333333
                        34    15         5    2.333333    1.000000  13.000000
                        35    20         4    1.666667    1.333333  13.000000
                        36    14         6    1.333333    1.666667  10.000000

                           sot_rolling dist_rolling fk_rolling  pk_rolling  \
team
Arsenal                 6     3.666667    14.733333   0.666667    0.000000
                        7     3.666667    15.766667   0.000000    0.000000
                        9     3.666667    16.733333   0.666667    0.000000
                        11    4.000000    16.033333   1.000000    0.000000
                        13    2.666667    18.033333   1.000000    0.333333
...                                ...          ...        ...         ...
Wolverhampton Wanderers 32    3.666667    19.300000   0.000000    0.000000
                        33    4.333333    19.600000   0.000000    0.000000
                        34    5.333333    19.833333   0.000000    0.000000
                        35    5.000000    18.533333   0.000000    0.000000
                        36    4.666667    17.633333   0.000000    0.000000

                            pkatt_rolling
team
Arsenal                 6        0.000000
                        7        0.000000
                        9        0.000000
                        11       0.000000
                        13       0.333333
...                                   ...
Wolverhampton Wanderers 32       0.000000
                        33       0.000000
                        34       0.000000
                        35       0.000000
                        36       0.000000

[1317 rows x 40 columns]

In [156]:
matches_rolling = matches_rolling.droplevel('team')

In [157]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2,1,Sheffield Utd,...,14,6,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0,1,Manchester City,...,17,5,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0,1,Leicester City,...,19,6,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
11,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1,0,Manchester Utd,...,16,6,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
13,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0,3,Aston Villa,...,19,6,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,2022-03-13,14:00,Premier League,Matchweek 29,Sun,Away,W,1,0,Everton,...,14,6,1.333333,1.000000,12.333333,3.666667,19.300000,0.000000,0.000000,0.000000
33,2022-03-18,20:00,Premier League,Matchweek 30,Fri,Home,L,2,3,Leeds United,...,20,4,1.666667,0.666667,12.333333,4.333333,19.600000,0.000000,0.000000,0.000000
34,2022-04-02,15:00,Premier League,Matchweek 31,Sat,Home,W,2,1,Aston Villa,...,15,5,2.333333,1.000000,13.000000,5.333333,19.833333,0.000000,0.000000,0.000000
35,2022-04-08,20:00,Premier League,Matchweek 32,Fri,Away,L,0,1,Newcastle Utd,...,20,4,1.666667,1.333333,13.000000,5.000000,18.533333,0.000000,0.000000,0.000000
36,2022-04-24,14:00,Premier League,Matchweek 34,Sun,Away,L,0,1,Burnley,...,14,6,1.333333,1.666667,10.000000,4.666667,17.633333,0.000000,0.000000,0.000000

In [158]:
matches_rolling.index = range(matches_rolling.shape[0])

In [159]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    precision = precision_score(test["target"], preds)
    return combined, error

In [160]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)

In [161]:
precision

0.625

In [162]:
combined

      actual  predicted
55         0          0
56         1          0
57         1          0
58         1          1
59         1          1
...      ...        ...
1312       1          0
1313       0          0
1314       1          0
1315       0          0
1316       0          0

[276 rows x 2 columns]

In [163]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [164]:
combined

,actual,predicted,date,team,opponent,result
55,0,0,2022-01-23,Arsenal,Burnley,D
56,1,0,2022-02-10,Arsenal,Wolves,W
57,1,0,2022-02-19,Arsenal,Brentford,W
58,1,1,2022-02-24,Arsenal,Wolves,W
59,1,1,2022-03-06,Arsenal,Watford,W
...,...,...,...,...,...,...
1312,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W
1313,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L
1314,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W
1315,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L
1316,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L

In [165]:
matches_rolling.index = range(matches_rolling.shape[0])

In [171]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", 
              "Manchester United": "Manchester Utd", 
              "Newcastle United": "Newcastle Utd", 
              "Tottenham Hotspur": "Tottenham", 
              "West Ham United": "West Ham", 
              "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [172]:
combined["new_team"] = combined["team"].map(mapping)

In [173]:
combined

,actual,predicted,date,team,opponent,result,new_team
55,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal
56,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal
57,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal
58,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal
59,1,1,2022-03-06,Arsenal,Watford,W,Arsenal
...,...,...,...,...,...,...,...
1312,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W,Wolves
1313,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L,Wolves
1314,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W,Wolves
1315,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L,Wolves
1316,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolves

In [174]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [169]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
1,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
2,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
3,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
4,1,1,2022-03-06,Arsenal,Watford,W,Arsenal,0,0,Watford,Arsenal,L,Watford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,1,0,2022-03-13,Wolverhampton Wanderers,Everton,W,Wolves,0,0,Everton,Wolves,L,Everton
258,0,0,2022-03-18,Wolverhampton Wanderers,Leeds United,L,Wolves,1,0,Leeds United,Wolves,W,Leeds United
259,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,0,Aston Villa,Wolves,L,Aston Villa
260,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L,Wolves,1,0,Newcastle United,Wolves,W,Newcastle Utd
261,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolves,1,0,Burnley,Wolves,W,Burnley

In [170]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

actual_x
1    27
0    13
Name: count, dtype: int64

In [175]:
27/40

0.675